name: Generate GitHub Profile Stats

on:
  push:
    branches: [main]
    paths-ignore:
      - github-metrics.svg
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.PROFILE_TOKEN }}
          user: Ja0Santana
          base: header, activity, community, repositories, metadata
          repositories: 100
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: false
          plugin_languages: yes
          plugin_languages_sections: most-used
          config_timezone: America/Sao_Paulo
